### ISSUE TITLE
Explanation on _addTodo() function

### ISSUE THREAD

**Issue by AhSem** [lesnitsky/todolist_flutter#3]
`
_addTodo() {
     showDialog(
       context: **context**,
       builder: (BuildContext context) {
         return AlertDialog(
           title: Text('New todo'),
        );
      },
    );
 }
`

Hi, referring to the function above, where does the **context** variable come from? It was not passed in as an argument. Why can we access to it?

I am completely new to Flutter.

Thank you.

**Comment by lesnitsky** [comment]
@AhSem context is a variable which is available in `build` of stateless widget or in `State`
[Read more here](https://api.flutter.dev/flutter/widgets/BuildContext-class.html) and [here](https://flutterbyexample.com/build-context-class/)
